/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminNav: typeof import('./src/components/Admin/nav.vue')['default']
    AdminSideBar: typeof import('./src/components/Admin/SideBar/index.vue')['default']
    AdminSideBarAdmin: typeof import('./src/components/Admin/SideBarAdmin.vue')['default']
    AdminSideBarItem: typeof import('./src/components/Admin/SideBar/item.vue')['default']
    AdminSideBarSideBarAdmin: typeof import('./src/components/Admin/SideBar/SideBarAdmin.vue')['default']
    AdminSideBarSideBarItem: typeof import('./src/components/Admin/SideBar/SideBarItem.vue')['default']
    CommonButton: typeof import('./src/components/Common/button.vue')['default']
    CommonPagination: typeof import('./src/components/Common/pagination.vue')['default']
    CommonSwitch: typeof import('./src/components/Common/switch.vue')['default']
    EditorMarkdown: typeof import('./src/components/Editor/markdown.vue')['default']
    EditorNormal: typeof import('./src/components/Editor/normal.vue')['default']
    ExperienceCanvasItem: typeof import('./src/components/Experience/Canvas/item.vue')['default']
    ExperienceFloatAction: typeof import('./src/components/Experience/FloatAction/index.vue')['default']
    ExperienceToolBarItem: typeof import('./src/components/Experience/ToolBar/item.vue')['default']
    GlobalNav: typeof import('./src/components/Global/Nav/index.vue')['default']
    IconComputer: typeof import('./src/components/Icon/computer.vue')['default']
    IconConfig: typeof import('./src/components/Icon/config.vue')['default']
    IconDynamic: typeof import('./src/components/Icon/dynamic.vue')['default']
    IconExit: typeof import('./src/components/Icon/exit.vue')['default']
    IconGateway: typeof import('./src/components/Icon/gateway.vue')['default']
    IconIconExit: typeof import('./src/components/Icon/IconExit.vue')['default']
    IconIconReturn: typeof import('./src/components/Icon/IconReturn.vue')['default']
    IconIconView: typeof import('./src/components/Icon/IconView.vue')['default']
    IconReturn: typeof import('./src/components/Icon/return.vue')['default']
    IconServer: typeof import('./src/components/Icon/server.vue')['default']
    IconView: typeof import('./src/components/Icon/view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
  }
}
