/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExperienceCanvasItem: typeof import('./src/components/Experience/Canvas/item.vue')['default']
    ExperienceFloatAction: typeof import('./src/components/Experience/FloatAction/index.vue')['default']
    ExperienceToolBarItem: typeof import('./src/components/Experience/ToolBar/item.vue')['default']
    GlobalNav: typeof import('./src/components/Global/Nav/index.vue')['default']
    IconComputer: typeof import('./src/components/Icon/computer.vue')['default']
    IconConfig: typeof import('./src/components/Icon/config.vue')['default']
    IconDynamic: typeof import('./src/components/Icon/dynamic.vue')['default']
    IconGateway: typeof import('./src/components/Icon/gateway.vue')['default']
    IconServer: typeof import('./src/components/Icon/server.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
  }
}
