/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminNav: typeof import('./src/components/Admin/nav.vue')['default']
    AdminSideBar: typeof import('./src/components/Admin/SideBar/index.vue')['default']
    AdminSideBarItem: typeof import('./src/components/Admin/SideBar/item.vue')['default']
    CommonButton: typeof import('./src/components/Common/button.vue')['default']
    CommonPagination: typeof import('./src/components/Common/pagination.vue')['default']
    CommonSwitch: typeof import('./src/components/Common/switch.vue')['default']
    EditorMarkdown: typeof import('./src/components/Editor/markdown.vue')['default']
    EditorNormal: typeof import('./src/components/Editor/normal.vue')['default']
    IconArrowLeft: typeof import('./src/components/Icon/arrow/left.vue')['default']
    IconArrowRight: typeof import('./src/components/Icon/arrow/right.vue')['default']
    IconChat: typeof import('./src/components/Icon/chat.vue')['default']
    IconClose: typeof import('./src/components/Icon/close.vue')['default']
    IconComment: typeof import('./src/components/Icon/comment.vue')['default']
    IconComputer: typeof import('./src/components/Icon/computer.vue')['default']
    IconConfig: typeof import('./src/components/Icon/config.vue')['default']
    IconDynamic: typeof import('./src/components/Icon/dynamic.vue')['default']
    IconEdit: typeof import('./src/components/Icon/edit.vue')['default']
    IconExit: typeof import('./src/components/Icon/exit.vue')['default']
    IconGateway: typeof import('./src/components/Icon/gateway.vue')['default']
    IconLikeOutline: typeof import('./src/components/Icon/like/outline.vue')['default']
    IconLikeSolid: typeof import('./src/components/Icon/like/solid.vue')['default']
    IconLoading: typeof import('./src/components/Icon/loading.vue')['default']
    IconPlay: typeof import('./src/components/Icon/play.vue')['default']
    IconReturn: typeof import('./src/components/Icon/return.vue')['default']
    IconServer: typeof import('./src/components/Icon/server.vue')['default']
    IconView: typeof import('./src/components/Icon/view.vue')['default']
    KBQA: typeof import('./src/components/KBQA/index.vue')['default']
    Nav: typeof import('./src/components/Nav/index.vue')['default']
    PostCommentReply: typeof import('./src/components/Post/commentReply.vue')['default']
    PostNew: typeof import('./src/components/Post/new.vue')['default']
    PostPreview: typeof import('./src/components/Post/preview.vue')['default']
    PostPreviewUser: typeof import('./src/components/Post/previewUser.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar/index.vue')['default']
    TryCanvasItem: typeof import('./src/components/Try/Canvas/item.vue')['default']
    TryFloatAction: typeof import('./src/components/Try/FloatAction/index.vue')['default']
    TryToolBarItem: typeof import('./src/components/Try/ToolBar/item.vue')['default']
  }
}
